export const SET_TILES_LIST = 'SET_TILES_LIST';
export const SET_TILE_FLIPPED = 'SET_TILE_FLIPPED';
export const UPDATE_TILE_FLIPPED = 'UPDATE_TILE_FLIPPED';
export const CLEAR_FLIPPED = 'CLEAR_FLIPPED';
export const SAVE_FLIPPED = 'SAVE_FLIPPED';
export const RESET_GAME = 'RESET_GAME';
